sudo: false
notifications:
  email: false
branches:
  only:
    - develop
language: node_js
node_js:
  - 8
script:
  - yarn install
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  local-dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
